### ISSUE TITLE
classes are broken, gh-pages, too

### ISSUE THREAD

**Issue by flying-sheep** [hadley/staticdocs#109]
in order to get something similar to the example in the (CSS-wise broken) page for [`render_template`](https://hadley.github.io/staticdocs/render_template.html) (which no longer is exported), i have to do this:

```r
rd <- staticdocs:::cached_parse_Rd(rd_path)  # no exported function accepting a file path, why?
html <- staticdocs:::to_html.Rd_doc(rd, package = pkg_name)
render_page(list(sd_path = ''), 'topic', html)  # i don’t need or want to use packages, only Rd files
```

this mirrors the way `to_html.Rd_doc` is used in [`build_topics`](https://github.com/hadley/staticdocs/blob/25c049fed445732d3afb158eeb485ad6ac6e925e/R/build.r#L72) on objects that are created via `cached_parse_Rd` and have the class `Rd_content`

it would be nice to

1. fix https://hadley.github.io
2. your `parse_rd` is too similar to `tools::parse_Rd`. please rename it to something like `parse_help_page` or so (as no `.Rd` file is parsed)
2. please remove the `Rd_doc` class and use the `Rd` class in its stead. this allows to use the output of `tools::parse_Rd` in `to_html`. The `set_classes` dance in the code is confusing, just let parsed things have the `Rd` class.
3. please allow to use `render_page` with a manually specified template path instead of a `sd_package` object

**Comment by hadley** [comment]
I think you're basically asking for a solid refactoring of `parse_rd()` with is unlikely to happen in the short term (and will be obvious in the long-term)

**Comment by hadley** [comment]
But I'd accept a PR!

**Comment by flying-sheep** [comment]
not, really, mainly i just want things to work without using private functions.

the list of steps was just a suggestion
