### ISSUE TITLE
Functions created and used in examples are mistaken for exported functions

### ISSUE THREAD

**Issue by bborgesr** [hadley/staticdocs#136]
As of right now, when you run staticdocs for the Shiny website, you get this type of input (partial):

```
Generating reactiveValuesToList.html
Generating registerInputHandler.html
Generating removeInputHandler.html
Generating removeUI.html
Generating renderDataTable.html
Generating renderImage.html
Generating renderPlot.html
Generating renderPrint.html
Can't find help topic 'visFun'
Can't find help topic 'invisFun'
Can't find help topic 'multiprintFun'
Can't find help topic 'nullFun'
Can't find help topic 'invisNullFun'
Can't find help topic 'vecFun'
Can't find help topic 'visFun'
Can't find help topic 'invisFun'
Can't find help topic 'multiprintFun'
Can't find help topic 'nullFun'
Can't find help topic 'invisNullFun'
Can't find help topic 'vecFun'
Generating renderTable.html
Generating renderText.html
Can't find help topic 'visFun'
Can't find help topic 'invisFun'
Can't find help topic 'multiprintFun'
Can't find help topic 'nullFun'
Can't find help topic 'invisNullFun'
Can't find help topic 'vecFun'
Can't find help topic 'visFun'
Can't find help topic 'invisFun'
Can't find help topic 'multiprintFun'
Can't find help topic 'nullFun'
Can't find help topic 'invisNullFun'
Can't find help topic 'vecFun'
Generating renderUI.html
Generating repeatable.html
Can't find help topic 'rnormA'
Can't find help topic 'rnormA'
Can't find help topic 'rnormA'
Can't find help topic 'rnormB'
Generating req.html
Generating restoreInput.html
Generating runApp.html
Generating runExample.html
Generating runGadget.html
Generating runUrl.html
Generating safeError.html
Generating selectInput.html
Generating serverInfo.html
Generating session.html
Generating setBookmarkExclude.html
Generating shiny-options.html
Generating shiny-package.html
Generating shinyApp.html
Generating shinyDeprecated.html
Generating shinyOptions.html
```

All of the functions that it says "Can't find help topic ..." are functions created and used in examples. I *think* this is somehow trying to generate help pages for functions created and used in examples - misreading them as exported functions? - (and failing since there's no documentation available). Obviously, we don't want these functions documented. While this doesn't seem to impact the final product (the website looks the same from the user's perspective), it does look like a bug...

I traced it back to [this commit](https://github.com/hadley/staticdocs/commit/4c7139bde2dccc85aa1b7a0c8433f05af62cba6e), in particlar, [this line](https://github.com/hadley/staticdocs/blob/master/R/highlight.r#L5):

```r
try(expr <- utils::getParseData(parse(text = text, keep.source = TRUE)))
```

If we change the last argument to `keep.source = FALSE`, then everything works as expected:

```r
Generating reactiveValuesToList.html
Generating registerInputHandler.html
Generating removeInputHandler.html
Generating removeUI.html
Generating renderDataTable.html
Generating renderImage.html
Generating renderPlot.html
Generating renderPrint.html
Generating renderTable.html
Generating renderText.html
Generating renderUI.html
Generating repeatable.html
Generating req.html
Generating restoreInput.html
Generating runApp.html
Generating runExample.html
Generating runGadget.html
Generating runUrl.html
Generating safeError.html
Generating selectInput.html
Generating serverInfo.html
Generating session.html
Generating setBookmarkExclude.html
Generating shiny-options.html
Generating shiny-package.html
Generating shinyApp.html
Generating shinyDeprecated.html
Generating shinyOptions.html
```

I don't quite understand the mechanism being used here (not super familiar with this part of the codebase)... Is there any reason why we'd ever want `keep.source = FALSE`. If not, the fix is obviously easy... But if there is a valid reason for that sometimes, maybe it should be an argument to `build_site`, or at the very least be left blank, so that the user can configure it using `options`, since the documentation for `parse` allows this: 

```r
parse(file = "", n = NULL, text = NULL, prompt = "?",
      keep.source = getOption("keep.source"), srcfile,
      encoding = "unknown")
```

**Comment by hadley** [comment]
You can just ignore the messages — they're because staticdocs tries to automatically link all function names in the docs to their corresponding doc page. Maybe I should just drop the message since it doesn't actually matter if that fails?

**Comment by bborgesr** [comment]
Ok, got it. Dropping the message might be the best... Although, maybe some people will find them useful..? At least, making the message optional might be helpful so the log doesn't get all cluttered up... Maybe make it an option (set with `options()` I mean) though, so we're not passing yet another argument..? But now that I understand where this is coming from, it doesn't bother me as much, so I'm fine if you don't change  it. I'd still prefer not seeing those messages in our specific case.

**Comment by bborgesr** [comment]
Aside: This linking up of all the functions was a great idea!
