### ISSUE TITLE
Author meta-tag is not filled

### ISSUE THREAD

**Issue by dfalbel** [hadley/staticdocs#142]
When you use the syntax `Authors@R:`  in DESCRIPTION file, the author meta-tag is not filled. 
However when you use `Author` syntax the tag is filled, but the Author field is not filled in the index page.

This answer tells you could add multiple author meta-tags 
http://stackoverflow.com/a/8589099/3297472

**Comment by hadley** [comment]
Is that really important?

**Comment by dfalbel** [comment]
Not really. Maybe the other site is more important: when you  use `Author` instead of `Author@R` the Author field is not used in the `index.html` (the one in the right side of the page).  

I was using `Author` notation in DESCRIPTION and the lack of the author name in the home page bothered me a little, that's why I changed to `Author@R`.

**Comment by hadley** [comment]
It's better to use that form anyway
