### ISSUE TITLE
redirect output `base_path` to `gh-pages` branch?

### ISSUE THREAD

**Issue by cboettig** [hadley/staticdocs#15]
It would be great to simply run `staticdocs` in, say, "gh-pages" mode such that the output immediately ends up on the gh-pages branch of the repository.  

More generally, perhaps I'm stuck more with a git problem than anything to do with staticdocs -- I haven't found a reliable way to run staticdocs on my `master` branch (say, sticking the output into `base_path="inst/doc/html"), and then switch to gh-pages branch and pull in just the html.  I tried [this solution suggested on SO](http://stackoverflow.com/questions/10590156/git-update-the-root-directory-of-a-branch-from-the-subdirectory-of-another) for a while, but found the commands a bit opaque and cannot troubleshoot when I get a gh-pages build error since I cannot even see actual files in the branch.  Do you have any suggestions on how to do this better? (Whether or not this is something that could be automated in staticdocs).   Much appreciated!

**Comment by hadley** [comment]
And now you can publish to `docs/` so I'm closing
