### ISSUE TITLE
error in html for S4method for operators

### ISSUE THREAD

**Issue by iagomosqueira** [hadley/staticdocs#153]
I am documenting an S4 method for `[`

```
setMethod("[", signature(x="FLArray"),
    function(x, i, j, k, l, m, n, ...) { 
[...]
})
```
for which roxygen generates

```
\usage{
\S4method{[}{FLArray,ANY,ANY,ANY}(x, i, j, k, l, m, n, ...)
}
```

which then staticdocs converts into

```
    <h2>Usage</h2>
    <pre><div># S4 method for FLArray,ANY,ANY,ANY
[(x, i, j, k, l, m, n, ..., drop&nbsp;=&nbsp;FALSE)</div>
</pre>
 ```
but I am getting this error

```
Error in parse(text = text, keep.source = TRUE) : 
  <text>:2:1: unexpected '['
1: # S4 method for FLArray,ANY,ANY,ANY
2: [
   ^
```

Can staticdocs deal with this? Or should I look at the issue in roxygen?

Same thing happens with a method for %*%.

Full code is at https://github.com/flr/FLCore/tree/mergeRoxygen (Files R/FLArray.R line 90, man/Extract.Rd and docs/Extract.html)

**Comment by hadley** [comment]
What does it look like when you look at in the regular docs?

**Comment by iagomosqueira** [comment]
This is what the help looks like in Rstudio
![extract rd](https://cloud.githubusercontent.com/assets/1029847/18928190/617776a6-85bf-11e6-8248-12a0da0ac7e6.png)

and if fact it looks OK too in the staticdocs html as far I can tell

![extract-html](https://cloud.githubusercontent.com/assets/1029847/18928189/61739112-85bf-11e6-817b-09f2c510d995.png)

**Comment by hadley** [comment]
That definitely does not look ok - it should be `x[y] <- value` not `[(x, y <- value`

**Comment by iagomosqueira** [comment]
Very true

**Comment by hadley** [comment]
Should no longer throw an error, even if it doesn't display quite right

**Comment by iagomosqueira** [comment]
Thanks. Any idea of what way to explore to get these methods displayed correctly?

**Comment by hadley** [comment]
It requires quite a bit of work in the parsing code to identify infix operators and format them differently.
