### ISSUE TITLE
equation rendering on HTML pages

### ISSUE THREAD

**Issue by jayhesselberth** [hadley/staticdocs#154]
Math equation behavior seems unexpected with the new staticdocs.

Equations in `\eqn{}` and `\deqn{}` tags from the Rd files are not rendered correctly on html pages (the equations appear as escaped functions, but aren't converted to math formats).

Simple equations like `$$ a + b $$` embedded in the Rd files appear OK.

However more complicated equations like:

`$$ J(x,y) = \frac{\mid x \bigcap y \mid} {\mid x \bigcup y \mid} $$`

generate `Unknown tag: UNKNOWN/tag` warnings using `staticdocs::build_site()`

**Comment by hadley** [comment]
You can't expect `$$` to work in `.Rd` files. You need to use `\eqn{}`, `\deqn{}`
