### ISSUE TITLE
Add option to remove/ignore \dontrun when generating staticdocs pages?

### ISSUE THREAD

**Issue by sckott** [hadley/staticdocs#29]
Hi Hadley, 

In almost all of our rOpenSci packages we make web API calls, and so our examples are almost all wrapped in \dontrun.  If we generate staticdocs pages, the examples then do not run. Is it possible to add an option in staticdocs to ignore \dontrun so that examples are run?

I wrote a little function to do this manually, but I'm sure you can come up with a much better solution:

nodontrun <- function(x) {
  dat <- readLines(x)
  dat[grep("@examples", dat)] <- "#' @examples"
  dat[grep("#' }", dat)] <- ""
  write(dat,  # change directory to one of interest
    paste("~newdirectory/R/", 
    x, sep=''))
}

files <- dir("pkgdirectory/R")
l_ply(files,  nodontrun) # which puts all .R files in a new directory

Then run roxygenize() (or document() ) on the .R files in that new directory

**Comment by hadley** [comment]
This is mostly a matter of adding an argument to `to_html.dontrun` so that it doesn't add the comments. Then you just need to thread that argument all the way down from `build_site()`.

**Comment by hadley** [comment]
Oh it's actually simpler than that - you just need to accept a `pkg` argument, which will get the package options.
