### ISSUE TITLE
dir.exists function does not exist

### ISSUE THREAD

**Issue by tomaskrehlik** [hadley/staticdocs#33]
Hello, I have been trying to build something with the recently updated package and it says that dir.exists function does not exist.

**Comment by dlebauer** [comment]
This issue still seems to occur - and @wch I don't see the function `dir.exists` in devtools ...

**Comment by dlebauer** [comment]
Another workaround

```
## R
dir.create("inst/staticdocs")
## shell
mkdir inst/staticdocs
```

**Comment by wch** [comment]
Hm, `dir.exists` is in devtools but not currently exported. It might have been un-exported at some point. I don't see a reason not to add the same function to staticdocs.

**Comment by gaborcsardi** [comment]
You don't actually really need `dir.exists` here, either just

1. Create the directory in the package you document. (You'll need to put a file in it as well if you use git, git does not track empty directories.). Or,
2. Add a `dir.create(..., showWarning = FALSE, recursive = TRUE)` to `staticdocs` itself.

**Comment by kenahoo** [comment]
`dir.exists` and `dir.create` are part of the `base` package.  `dir.exists` was added in R 3.2.0.  `dir.create` has been there since R 0.90.1.
