### ISSUE TITLE
Text of value section rendered as paragraphs rather than describe/dl

### ISSUE THREAD

**Issue by BrianDiggs** [hadley/staticdocs#37]
According to "Writing R Extensions"

> \value{...}
>    Description of the function's return value.
>
>    If a list with multiple values is returned, you can use entries of the form
>
>              \item{comp_i}{Description of comp_i.}
>
>    for each component of the list returned. Optional text may precede56 this list (see for example the help for rle). Note that \value is implicitly a \describe environment, so that environment should not be used for listing components, just individual \item{}{} entries. 

However, they are not being rendered that way. An example is in `ggplot2::stat_summary`. The relevant section of the roxygen source:

```r
#' @return a data.frame with additional columns:
#' \item{fun.data}{Complete summary function. Should take data frame as
#' input and return data frame as output}
#' \item{fun.ymin}{ymin summary function (should take numeric vector and
#' return single number)}
#' \item{fun.y}{y summary function (should take numeric vector and return
#' single number)}
#' \item{fun.ymax}{ymax summary function (should take numeric vector and
#' return single number)}
```

The corresponding `.Rd` file:

```
\value{
  a data.frame with additional columns:
  \item{fun.data}{Complete summary function. Should take
  data frame as input and return data frame as output}
  \item{fun.ymin}{ymin summary function (should take
  numeric vector and return single number)} \item{fun.y}{y
  summary function (should take numeric vector and return
  single number)} \item{fun.ymax}{ymax summary function
  (should take numeric vector and return single number)}
}
```

The corresponding HTML (from http://docs.ggplot2.org/0.9.3/stat_summary.html)

```html
    <div class="Value">
      <h2>Value</h2>
      
      <p>a data.frame with additional columns:
  fun.dataComplete summary function. Should take
  data frame as input and return data frame as output
  fun.yminymin summary function (should take
  numeric vector and return single number) fun.yy
  summary function (should take numeric vector and return
  single number) fun.ymaxymax summary function
  (should take numeric vector and return single number)</p>
  
    </div>
```

This is in contrast with the `\arguments` section which is similarly formatted in the `.Rd` file, but rendered in a `<dl>`.

**Comment by hadley** [comment]
I'm pretty sure this is fixed now — that doc page doesn't use `\value{}` anymore, but the code looks reasonable.
