### ISSUE TITLE
inherits argument in sd_icon() only follows one level

### ISSUE THREAD

**Issue by wch** [hadley/staticdocs#41]
In the ggplot2 docs, the icon for `stat_density2d` inherits from `geom_density2d`, which in turn inherits from `geom_contour`. The code for `icon_path` only follows one level of inheritance, and so the generated page points to the nonexistent file `geom_density2d.png`: 
http://docs.ggplot2.org/0.9.3.1/

Edit: I manually edited the ggplot2 docs webpage so that the icon for stat_density2d looks right, but that obviously didn't affect the underlying issue.

**Comment by hadley** [comment]
By design
