### ISSUE TITLE
Run in non-interactive mode

### ISSUE THREAD

**Issue by hadley** [hadley/staticdocs#6]
Probably through `devtools::R`

**Comment by hadley** [comment]
I have no idea what this means now.

**Comment by nteetor** [comment]
I'm wondering if I am running into this issue now. 

My package's examples include shiny apps which I have surrounded with `if (interactive()) { .. }`. For building out package Rd docs there are no issues. However, when trying to build a site with pkgdown while working in RStudio the build process is understandably interrupted as `interactive()` is true. Could this be what you meant by "run in non-interactive mode"?

**Comment by hadley** [comment]
You can use the add-in to run in a separate process.

**Comment by nteetor** [comment]
Excellent! My apologies for not seeing that sooner.
