### ISSUE TITLE
"Don't run" examples do not render properly

### ISSUE THREAD

**Issue by eibanez** [hadley/staticdocs#73]
When a don't run example is present, staticdocs will render it on the browser as follows:

```
## <strong>Not run</strong>: process_folder()
```

The problem is that the example line is added the `<strong>` tags in `to_html.dontrun` but it ultimately ends up in `replay_html.source`, where the `<` and `>` symbols are escaped (by `escape_html`). In the end `<strong>` is coded as `&lt;strong&gt;`

I'm going to propose a pull request that restores the correct symbols, but it's definitely a temporary patch to this problem.

**Comment by eibanez** [comment]
@jcheng5 I think this is an unintended consequence of #52.

**Comment by jcheng5** [comment]
I think the easy answer is just to remove the strong tags from "Not run". A harder but more complete fix would be to use htmltools to generate the HTML, which would let escaped and unescaped strings coexist happily--but that would be a significant refactoring.

**Comment by eibanez** [comment]
Sounds good. I'll update the PR.

**Comment by jranke** [comment]
@eibanez : I think this can be closed now, after #88 has been merged.
