### ISSUE TITLE
How to run to include plots

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/staticdocs#76]
If I do 
```
Rscript -e 'staticdocs::build_site()`
```
then they are not included. Do I need to run it interactively? Just because I am planning to run it on Travis, by https://github.com/metacran/r-builder.

**Comment by mbacou** [comment]
Same question as @gaborcsardi

**Comment by jranke** [comment]
Yes, if you run it interactively, the plots are included. I believe that's why we have issue #6 open.

**Comment by hadley** [comment]
Maybe you just need `R -e "staticdocs::build_site(examples = TRUE)"`?  That's what works for ggplot2.
