### ISSUE TITLE
Option to skip demos?

### ISSUE THREAD

**Issue by wrathematics** [hadley/staticdocs#86]
This may exist and I just can't find it, but I would find it very useful to either be able to outright skip demos or preferably just list the raw content without actually running them.

This is particularly a problem for me because our various MPI packages have demos that are not meant to be run interactively.  So after the first is run and calls `MPI_FINALIZE` via `finalize()`, the later demos can not be run:

```
Rendering demos
*** The MPI_Comm_set_errhandler() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[wootabega-laptop:29826] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by hadley** [comment]
Fixed in #99
