### ISSUE TITLE
staticdocs R package build_site function causes dependent packages unable to be loaded

### ISSUE THREAD

**Issue by MarcinKosinski** [hadley/staticdocs#98]
Problem is described here
http://stackoverflow.com/questions/36874972/staticdocs-r-package-build-site-function-causes-dependent-packages-unable-to-be

Any answer would be helpful :).

**Comment by hadley** [comment]
Probably caused by the way that `load_all()` works. If this is causing you problems, just call `build_site()` in a separate process.

**Comment by MarcinKosinski** [comment]
The main problem is that I can not create examples for which I load a packages that depends on mine core package.

![pkgdown_tries](https://cloud.githubusercontent.com/assets/6773454/21229316/82127384-c2e1-11e6-8a5d-9c33f17d0dea.png)


The issue with not being able to load those packages later in the RStudio console isn't so problematic.

**Comment by MarcinKosinski** [comment]
It looks like I have found a nasty work-around.
`RTCGA` software package uses 8 data packages in its examples. Each data package required RTCGA to be loaded. `pkgdown::build_site()` uses `devtools::load_all()` which weirdly loads only objects from RTCGA but does not allow to load this package during examples run. 

I have removed `RTCGA` from `Depends` of the data packages by changing those packages meta-informations like

````{r}

    packages_to_remove_RTCGA_from_Depends <- 
      c("RTCGA.clinical",
        "RTCGA.mutations",
        "RTCGA.rnaseq",
        "RTCGA.RPPA",
        "RTCGA.mRNA",
        "RTCGA.miRNASeq",
        "RTCGA.methylation",
        "RTCGA.CNV")
    
    sapply(packages_to_remove_RTCGA_from_Depends, function(data_package){
      Meta <- readRDS(file.path(.libPaths()[1], data_package, "Meta", "package.rds"))
      Meta$Depends <- list()
      saveRDS(Meta, file.path(.libPaths()[1], data_package, "Meta", "package.rds"))
    })
````
